<a href="https://colab.research.google.com/github/jsnsus789/tugas_besar_data_science/blob/main/tugas_besar_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Data Cleaning and Data Processing

Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import Dataset

In [9]:
df = pd.read_csv('Marketing_Campaign_Data_A-21492758-f47a-4913-971e-68c9a721311a.csv')
df.head()

Unnamed: 0  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0       58785       0         Cash loans           F            Y   
1      166116       0         Cash loans           F            N   
2      170111       0         Cash loans           F            Y   
3      184247       0         Cash loans           F            N   
4       75886       0         Cash loans           M            Y   

  FLAG_OWN_REALTY  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0               Y          157500.0    225000.0      11781.0         225000.0   
1               Y          180000.0    508495.5      21672.0         454500.0   
2               Y          360000.0    639396.0      47934.0         571500.0   
3               Y          162000.0    254700.0      14751.0         225000.0   
4               Y          225000.0    787131.0      42066.0         679500.0   

             NAME_EDUCATION_TYPE  NAME_HOUSING_TYPE  \
0  Secondary / secondary special  House / apartment   
1  Secondary / secondary special  House / apartment   
2              Incomplete higher  House / apartment   
3               Higher education  House / apartment   
4               Higher education  House / apartment   

   REGION_POPULATION_RELATIVE  REGION_RATING_CLIENT_W_CITY  \
0                    0.014520                            2   
1                    0.031329                            2   
2                    0.032561                            1   
3                    0.010147                            2   
4                    0.025164                            2   

         APPL_DATETIME  DATE_BIRTH  
0  2016-06-11 17:28:54  17-07-1959  
1  2015-05-22 08:42:03  23-06-1951  
2  2016-11-26 20:54:07  07-06-1979  
3  2017-02-20 09:22:06  20-07-1958  
4  2017-02-28 09:38:45  05-08-1985

Data Description

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30722 entries, 0 to 30721
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Unnamed: 0                   30722 non-null  int64  
 1   TARGET                       30722 non-null  int64  
 2   NAME_CONTRACT_TYPE           30722 non-null  object 
 3   CODE_GENDER                  30722 non-null  object 
 4   FLAG_OWN_CAR                 30722 non-null  object 
 5   FLAG_OWN_REALTY              30722 non-null  object 
 6   AMT_INCOME_TOTAL             30722 non-null  float64
 7   AMT_CREDIT                   30722 non-null  float64
 8   AMT_ANNUITY                  30722 non-null  float64
 9   AMT_GOODS_PRICE              30722 non-null  float64
 10  NAME_EDUCATION_TYPE          30722 non-null  object 
 11  NAME_HOUSING_TYPE            30722 non-null  object 
 12  REGION_POPULATION_RELATIVE   30722 non-null  float64
 13  REGION_RATING_CL

Detecting Missing Values

In [11]:
df.isnull()

Unnamed: 0  TARGET  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  \
0           False   False               False        False         False   
1           False   False               False        False         False   
2           False   False               False        False         False   
3           False   False               False        False         False   
4           False   False               False        False         False   
...           ...     ...                 ...          ...           ...   
30717       False   False               False        False         False   
30718       False   False               False        False         False   
30719       False   False               False        False         False   
30720       False   False               False        False         False   
30721       False   False               False        False         False   

       FLAG_OWN_REALTY  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                False             False       False        False   
1                False             False       False        False   
2                False             False       False        False   
3                False             False       False        False   
4                False             False       False        False   
...                ...               ...         ...          ...   
30717            False             False       False        False   
30718            False             False       False        False   
30719            False             False       False        False   
30720            False             False       False        False   
30721            False             False       False        False   

       AMT_GOODS_PRICE  NAME_EDUCATION_TYPE  NAME_HOUSING_TYPE  \
0                False                False              False   
1                False                False              False   
2                False                False              False   
3                False                False              False   
4                False                False              False   
...                ...                  ...                ...   
30717            False                False              False   
30718            False                False              False   
30719            False                False              False   
30720            False                False              False   
30721            False                False              False   

       REGION_POPULATION_RELATIVE  REGION_RATING_CLIENT_W_CITY  APPL_DATETIME  \
0                           False                        False          False   
1                           False                        False          False   
2                           False                        False          False   
3                           False                        False          False   
4                           False                        False          False   
...                           ...                          ...            ...   
30717                       False                        False          False   
30718                       False                        False          False   
30719                       False                        False          False   
30720                       False                        False          False   
30721                       False                        False          False   

       DATE_BIRTH  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
30717       False  
30718       False  
30719       False  
30720       False  
30721       False  

[30722 rows x 16 columns]

In [13]:
df.isnull().sum()

Unnamed: 0                     0
TARGET                         0
NAME_CONTRACT_TYPE             0
CODE_GENDER                    0
FLAG_OWN_CAR                   0
FLAG_OWN_REALTY                0
AMT_INCOME_TOTAL               0
AMT_CREDIT                     0
AMT_ANNUITY                    0
AMT_GOODS_PRICE                0
NAME_EDUCATION_TYPE            0
NAME_HOUSING_TYPE              0
REGION_POPULATION_RELATIVE     0
REGION_RATING_CLIENT_W_CITY    0
APPL_DATETIME                  0
DATE_BIRTH                     0
dtype: int64

Jadi, data tersebut tidak memiliki missing values.

# 2) Logistic Regression Method

In [15]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

In [16]:
# Kolom Variabel Independen dan Dependen
df.columns

Index(['Unnamed: 0', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'AMT_INCOME_TOTAL', 'AMT_CREDIT',
       'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_EDUCATION_TYPE',
       'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE',
       'REGION_RATING_CLIENT_W_CITY', 'APPL_DATETIME', 'DATE_BIRTH'],
      dtype='object')

In [19]:
# Splitting Data
# X = TARGET & AMT_ANNUITY
# Y = REGION_RATING_CLIENT_W_CITY

column = ["TARGET","AMT_ANNUITY"]
X = df[column]
Y = df.REGION_RATING_CLIENT_W_CITY
X.head()

TARGET  AMT_ANNUITY
0       0      11781.0
1       0      21672.0
2       0      47934.0
3       0      14751.0
4       0      42066.0

Teknik splitting data dengan Scikit-Learn
Training  80%  dan Testing  20%

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [21]:
print(X_test)

       TARGET  AMT_ANNUITY
20589       0      36094.5
12389       0      48631.5
19803       0      39771.0
29927       1      27193.5
11903       0       8059.5
...       ...          ...
20094       0      15115.5
25200       0      23305.5
19064       0      21748.5
17843       0      10944.0
5197        0      11029.5

[6145 rows x 2 columns]


Gunakan Metode Newton

Define input problem  $β0=[0,0.01,0.01]$ ,  $TOL=10^{-5}$  and  $N=100$  iterations

In [22]:
Beta = [0. ,0.01, 0.01]
TOL = 10**(-5)
N = 100

In [24]:
# Nyatakan dalam bentuk Matriks

dfy = Y_test
dfx = X_test
dfx['ones'] = np.ones(len(dfy))
A = dfx.reindex(columns=["ones","TARGET","AMT_ANNUITY"])
A = A.to_numpy()

#print(A)
Y = np.transpose(dfy.to_numpy()).flatten()
print(Y)

[2 2 2 ... 2 2 2]


In [25]:
# Definisikan Galat

def error(a,b):
  return np.min(np.absolute(a-b))

In [26]:
# Definisikan Fungsi Sigmoid

def Pi_func(A,B):
  Z= A@B
  return np.exp(Z)/(1+np.exp(Z))

In [27]:
# Solution of Newton's Method

#step 1
k= 1
Beta0=np.ones(len(Beta)) #pilih nilai sembarang tidak sama dengan x untuk lolos pada loop while

print('iter', 'x1  x2', 'error')
print(k-1,Beta, error(Beta,Beta0))

#Step 2
while (error(Beta,Beta0)>TOL) and (k < N):
  Pr = Pi_func(A,Beta)
  var = Pr*(np.ones(len(Pr))-Pr)
  V = np.diag(var)
  #step 3
  Fx = -A.T@(Y-Pr)
  Jac = A.T@V@A
  #step 4
  term = np.linalg.inv(Jac)@Fx
  Beta0 = Beta
  #step 5
  Beta = Beta0 - term
  #step 6
  k = k + 1
  print(k - 1,Beta, error(Beta,Beta0))

iter x1  x2 error
0 [0.0, 0.01, 0.01] 0.99
1 [nan nan nan] nan


<ipython-input-26-b2f3df460f1b>:5: RuntimeWarning: overflow encountered in exp
  return np.exp(Z)/(1+np.exp(Z))
<ipython-input-26-b2f3df460f1b>:5: RuntimeWarning: invalid value encountered in divide
  return np.exp(Z)/(1+np.exp(Z))


In [28]:
# Define Class Prediction

# A disini adalah A testing
Pr = Pi_func(A,Beta)
Y_predic = np.array([])
for a in Pr:
  if a <=0.5:
    Y_predic = np.append(Y_predic, 0)
  else:
     Y_predic = np.append(Y_predic, 1)

print(Y_predic)

[1. 1. 1. ... 1. 1. 1.]


In [29]:
# Confusion Matrix

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y, Y_predic))

[[ 679    0    0]
 [4575    0    0]
 [ 891    0    0]]


In [30]:
print(classification_report(Y, Y_predic))

              precision    recall  f1-score   support

           1       0.11      1.00      0.20       679
           2       0.00      0.00      0.00      4575
           3       0.00      0.00      0.00       891

    accuracy                           0.11      6145
   macro avg       0.04      0.33      0.07      6145
weighted avg       0.01      0.11      0.02      6145



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Naive Bayes Method

In [31]:
# Splitting Data

# Splitting Data
# X = TARGET & AMT_ANNUITY
# Y = REGION_RATING_CLIENT_W_CITY

column = ["TARGET","AMT_ANNUITY"]
X = df[column]
Y = df.REGION_RATING_CLIENT_W_CITY
X.head()

TARGET  AMT_ANNUITY
0       0      11781.0
1       0      21672.0
2       0      47934.0
3       0      14751.0
4       0      42066.0

Teknik splitting data dengan Scikit-Learn Training 80% dan Testing 20%

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [33]:
print(X_test)

       TARGET  AMT_ANNUITY
5654        0      61875.0
3141        0      17874.0
25269       0      15259.5
1577        1      10678.5
9034        0      21168.0
...       ...          ...
8970        0      30078.0
20180       0      33246.0
20163       0      30946.5
2145        0      20020.5
16953       0      28728.0

[6145 rows x 2 columns]


Training Model

In [ ]:
from sklearn.naive_bayes import GaussianNB

model_NB = GaussianNB()
model_NB

In [35]:
# Solution of Naive Bayes Method

import numpy as np
model_NB.fit(X_train,Y_train)

Y_pred_NB=model_NB.predict(X_test)

print(Y_pred_NB)
print(np.array(Y_test))

[2 2 2 ... 2 2 2]
[2 2 2 ... 2 2 3]


Evaluation

In [38]:
# Confusion Matrix

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, Y_pred_NB))

[[  45  653    0]
 [  63 4508    0]
 [  10  866    0]]


In [39]:
print(classification_report(Y_test, Y_pred_NB))

              precision    recall  f1-score   support

           1       0.38      0.06      0.11       698
           2       0.75      0.99      0.85      4571
           3       0.00      0.00      0.00       876

    accuracy                           0.74      6145
   macro avg       0.38      0.35      0.32      6145
weighted avg       0.60      0.74      0.65      6145



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
